name: Notificaci贸n a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Enviar notificaci贸n a ntfy.sh
        run: |
          curl -H "Title: Push a main por ${{ Robertson(Baltero) }}" \
               -H "Priority: high" \
               -d "El usuario ${{ Robertson(Baltero) }} ha subido c贸digo nuevo a la rama main del repositorio HolaMundoCS." \
               https://ntfy.sh/devops-itla
